map1 = [
    [],
    [
        ["1",["1","195 W Oakland Ave",],]
    ],
    [
        ["2", ["2", "2530 S 500 E", "Salt Lake City", "UT", "84106", "EOD", "44", "None"],]
    ],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
]


map2 = [
    [
        "11",
        [
            "11",
            "",
            "2600 Taylorsville Blvd",
            "Salt Lake City",
            "UT",
            "84118",
            "EOD",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "22",
        [
            "22",
            "",
            "6351 South 900 East",
            "Murray",
            "UT",
            "84121",
            "EOD",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "33",
        [
            "33",
            "",
            "2530 S 500 E",
            "Salt Lake City",
            "UT",
            "84106",
            "EOD",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "1",
        [
            "1",
            "",
            "195 W Oakland Ave",
            "Salt Lake City",
            "UT",
            "84115",
            "10:30:00",
            "21",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "12",
        [
            "12",
            "",
            "3575 W Valley Central Station bus Loop",
            "West Valley City",
            "UT",
            "84119",
            "EOD",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "23",
        [
            "23",
            "",
            "5100 South 2700 West",
            "Salt Lake City",
            "UT",
            "84118",
            "EOD",
            "5",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "34",
        [
            "34",
            "",
            "4580 S 2300 E",
            "Holladay",
            "UT",
            "84117",
            "10:30:00",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "2",
        [
            "2",
            "",
            "2530 S 500 E",
            "Salt Lake City",
            "UT",
            "84106",
            "EOD",
            "44",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "13",
        [
            "13",
            "",
            "2010 W 500 S",
            "Salt Lake City",
            "UT",
            "84104",
            "10:30:00",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "24",
        [
            "24",
            "",
            "5025 State St",
            "Murray",
            "UT",
            "84107",
            "EOD",
            "7",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "35",
        [
            "35",
            "",
            "1060 Dalton Ave S",
            "Salt Lake City",
            "UT",
            "84104",
            "EOD",
            "88",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "3",
        [
            "3",
            "",
            "233 Canyon Rd",
            "Salt Lake City",
            "UT",
            "84103",
            "EOD",
            "2",
            "Can only be on truck 2",
            "",
            "At hub",
        ],
    ],
    [
        "14",
        [
            "14",
            "",
            "4300 S 1300 E",
            "Millcreek",
            "UT",
            "84117",
            "10:30:00",
            "88",
            "Must be delivered with 15 & 19",
            "",
            "At hub",
        ],
    ],
    [
        "25",
        [
            "25",
            "",
            "5383 South 900 East #104",
            "Salt Lake City",
            "UT",
            "84117",
            "10:30:00",
            "7",
            "Delayed on flight---will not arrive to depot until 9:05 am",
            "",
            "At hub",
        ],
    ],
    [
        "36",
        [
            "36",
            "",
            "2300 Parkway Blvd",
            "West Valley City",
            "UT",
            "84119",
            "EOD",
            "88",
            "Can only be on truck 2",
            "",
            "At hub",
        ],
    ],
    [
        "4",
        [
            "4",
            "",
            "380 W 2880 S",
            "Salt Lake City",
            "UT",
            "84115",
            "EOD",
            "4",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "15",
        [
            "15",
            "",
            "4580 S 2300 E",
            "Holladay",
            "UT",
            "84117",
            "9:00:00",
            "4",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "26",
        [
            "26",
            "",
            "5383 South 900 East #104",
            "Salt Lake City",
            "UT",
            "84117",
            "EOD",
            "25",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "37",
        [
            "37",
            "",
            "410 S State St",
            "Salt Lake City",
            "UT",
            "84111",
            "10:30:00",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "5",
        [
            "5",
            "",
            "410 S State St",
            "Salt Lake City",
            "UT",
            "84111",
            "EOD",
            "5",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "16",
        [
            "16",
            "",
            "4580 S 2300 E",
            "Holladay",
            "UT",
            "84117",
            "10:30:00",
            "88",
            "Must be delivered with 13 & 19",
            "",
            "At hub",
        ],
    ],
    [
        "27",
        [
            "27",
            "",
            "1060 Dalton Ave S",
            "Salt Lake City",
            "UT",
            "84104",
            "EOD",
            "5",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "38",
        [
            "38",
            "",
            "410 S State St",
            "Salt Lake City",
            "UT",
            "84111",
            "EOD",
            "9",
            "Can only be on truck 2",
            "",
            "At hub",
        ],
    ],
    [
        "6",
        [
            "6",
            "",
            "3060 Lester St",
            "West Valley City",
            "UT",
            "84119",
            "10:30:00",
            "88",
            "Delayed on flight---will not arrive to depot until 9:05 am",
            "",
            "At hub",
        ],
    ],
    [
        "17",
        [
            "17",
            "",
            "3148 S 1100 W",
            "Salt Lake City",
            "UT",
            "84119",
            "EOD",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "28",
        [
            "28",
            "",
            "2835 Main St",
            "Salt Lake City",
            "UT",
            "84115",
            "EOD",
            "7",
            "Delayed on flight---will not arrive to depot until 9:05 am",
            "",
            "At hub",
        ],
    ],
    [
        "39",
        [
            "39",
            "",
            "2010 W 500 S",
            "Salt Lake City",
            "UT",
            "84104",
            "EOD",
            "9",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "7",
        [
            "7",
            "",
            "1330 2100 S",
            "Salt Lake City",
            "UT",
            "84106",
            "EOD",
            "8",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "18",
        [
            "18",
            "",
            "1488 4800 S",
            "Salt Lake City",
            "UT",
            "84123",
            "EOD",
            "6",
            "Can only be on truck 2",
            "",
            "At hub",
        ],
    ],
    [
        "29",
        [
            "29",
            "",
            "1330 2100 S",
            "Salt Lake City",
            "UT",
            "84106",
            "10:30:00",
            "2",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "40",
        [
            "40",
            "",
            "380 W 2880 S",
            "Salt Lake City",
            "UT",
            "84115",
            "10:30:00",
            "45",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "8",
        [
            "8",
            "",
            "300 State St",
            "Salt Lake City",
            "UT",
            "84103",
            "EOD",
            "9",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "19",
        [
            "19",
            "",
            "177 W Price Ave",
            "Salt Lake City",
            "UT",
            "84115",
            "EOD",
            "37",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "30",
        [
            "30",
            "",
            "300 State St",
            "Salt Lake City",
            "UT",
            "84103",
            "10:30:00",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "9",
        [
            "9",
            "",
            "410 S State St",
            "Salt Lake City",
            "UT",
            "84111",
            "EOD",
            "2",
            "Wrong address listed",
            "",
            "At hub",
        ],
    ],
    [
        "20",
        [
            "20",
            "",
            "3595 Main St",
            "Salt Lake City",
            "UT",
            "84115",
            "10:30:00",
            "37",
            "Must be delivered with 13 & 15",
            "",
            "At hub",
        ],
    ],
    [
        "31",
        [
            "31",
            "",
            "3365 S 900 W",
            "Salt Lake City",
            "UT",
            "84119",
            "10:30:00",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "10",
        [
            "10",
            "",
            "600 E 900 South",
            "Salt Lake City",
            "UT",
            "84105",
            "EOD",
            "1",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "21",
        [
            "21",
            "",
            "3595 Main St",
            "Salt Lake City",
            "UT",
            "84115",
            "EOD",
            "3",
            "None",
            "",
            "At hub",
        ],
    ],
    [
        "32",
        [
            "32",
            "",
            "3365 S 900 W",
            "Salt Lake City",
            "UT",
            "84119",
            "EOD",
            "1",
            "Delayed on flight---will not arrive to depot until 9:05 am",
            "",
            "At hub",
        ],
    ],
]

map3 = [
    [
        [
            "11",
            [
                "11",
                "",
                "2600 Taylorsville Blvd",
                "Salt Lake City",
                "UT",
                "84118",
                "EOD",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "22",
            [
                "22",
                "",
                "6351 South 900 East",
                "Murray",
                "UT",
                "84121",
                "EOD",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "33",
            [
                "33",
                "",
                "2530 S 500 E",
                "Salt Lake City",
                "UT",
                "84106",
                "EOD",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "1",
            [
                "1",
                "",
                "195 W Oakland Ave",
                "Salt Lake City",
                "UT",
                "84115",
                "10:30:00",
                "21",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "12",
            [
                "12",
                "",
                "3575 W Valley Central Station bus Loop",
                "West Valley City",
                "UT",
                "84119",
                "EOD",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "23",
            [
                "23",
                "",
                "5100 South 2700 West",
                "Salt Lake City",
                "UT",
                "84118",
                "EOD",
                "5",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "34",
            [
                "34",
                "",
                "4580 S 2300 E",
                "Holladay",
                "UT",
                "84117",
                "10:30:00",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "2",
            [
                "2",
                "",
                "2530 S 500 E",
                "Salt Lake City",
                "UT",
                "84106",
                "EOD",
                "44",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "13",
            [
                "13",
                "",
                "2010 W 500 S",
                "Salt Lake City",
                "UT",
                "84104",
                "10:30:00",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "24",
            [
                "24",
                "",
                "5025 State St",
                "Murray",
                "UT",
                "84107",
                "EOD",
                "7",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "35",
            [
                "35",
                "",
                "1060 Dalton Ave S",
                "Salt Lake City",
                "UT",
                "84104",
                "EOD",
                "88",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "3",
            [
                "3",
                "",
                "233 Canyon Rd",
                "Salt Lake City",
                "UT",
                "84103",
                "EOD",
                "2",
                "Can only be on truck 2",
                "",
                "At hub",
            ],
        ],
        [
            "14",
            [
                "14",
                "",
                "4300 S 1300 E",
                "Millcreek",
                "UT",
                "84117",
                "10:30:00",
                "88",
                "Must be delivered with 15 & 19",
                "",
                "At hub",
            ],
        ],
        [
            "25",
            [
                "25",
                "",
                "5383 South 900 East #104",
                "Salt Lake City",
                "UT",
                "84117",
                "10:30:00",
                "7",
                "Delayed on flight---will not arrive to depot until 9:05 am",
                "",
                "At hub",
            ],
        ],
        [
            "36",
            [
                "36",
                "",
                "2300 Parkway Blvd",
                "West Valley City",
                "UT",
                "84119",
                "EOD",
                "88",
                "Can only be on truck 2",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "4",
            [
                "4",
                "",
                "380 W 2880 S",
                "Salt Lake City",
                "UT",
                "84115",
                "EOD",
                "4",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "15",
            [
                "15",
                "",
                "4580 S 2300 E",
                "Holladay",
                "UT",
                "84117",
                "9:00:00",
                "4",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "26",
            [
                "26",
                "",
                "5383 South 900 East #104",
                "Salt Lake City",
                "UT",
                "84117",
                "EOD",
                "25",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "37",
            [
                "37",
                "",
                "410 S State St",
                "Salt Lake City",
                "UT",
                "84111",
                "10:30:00",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "5",
            [
                "5",
                "",
                "410 S State St",
                "Salt Lake City",
                "UT",
                "84111",
                "EOD",
                "5",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "16",
            [
                "16",
                "",
                "4580 S 2300 E",
                "Holladay",
                "UT",
                "84117",
                "10:30:00",
                "88",
                "Must be delivered with 13 & 19",
                "",
                "At hub",
            ],
        ],
        [
            "27",
            [
                "27",
                "",
                "1060 Dalton Ave S",
                "Salt Lake City",
                "UT",
                "84104",
                "EOD",
                "5",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "38",
            [
                "38",
                "",
                "410 S State St",
                "Salt Lake City",
                "UT",
                "84111",
                "EOD",
                "9",
                "Can only be on truck 2",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "6",
            [
                "6",
                "",
                "3060 Lester St",
                "West Valley City",
                "UT",
                "84119",
                "10:30:00",
                "88",
                "Delayed on flight---will not arrive to depot until 9:05 am",
                "",
                "At hub",
            ],
        ],
        [
            "17",
            [
                "17",
                "",
                "3148 S 1100 W",
                "Salt Lake City",
                "UT",
                "84119",
                "EOD",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "28",
            [
                "28",
                "",
                "2835 Main St",
                "Salt Lake City",
                "UT",
                "84115",
                "EOD",
                "7",
                "Delayed on flight---will not arrive to depot until 9:05 am",
                "",
                "At hub",
            ],
        ],
        [
            "39",
            [
                "39",
                "",
                "2010 W 500 S",
                "Salt Lake City",
                "UT",
                "84104",
                "EOD",
                "9",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "7",
            [
                "7",
                "",
                "1330 2100 S",
                "Salt Lake City",
                "UT",
                "84106",
                "EOD",
                "8",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "18",
            [
                "18",
                "",
                "1488 4800 S",
                "Salt Lake City",
                "UT",
                "84123",
                "EOD",
                "6",
                "Can only be on truck 2",
                "",
                "At hub",
            ],
        ],
        [
            "29",
            [
                "29",
                "",
                "1330 2100 S",
                "Salt Lake City",
                "UT",
                "84106",
                "10:30:00",
                "2",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "40",
            [
                "40",
                "",
                "380 W 2880 S",
                "Salt Lake City",
                "UT",
                "84115",
                "10:30:00",
                "45",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "8",
            [
                "8",
                "",
                "300 State St",
                "Salt Lake City",
                "UT",
                "84103",
                "EOD",
                "9",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "19",
            [
                "19",
                "",
                "177 W Price Ave",
                "Salt Lake City",
                "UT",
                "84115",
                "EOD",
                "37",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "30",
            [
                "30",
                "",
                "300 State St",
                "Salt Lake City",
                "UT",
                "84103",
                "10:30:00",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "9",
            [
                "9",
                "",
                "410 S State St",
                "Salt Lake City",
                "UT",
                "84111",
                "EOD",
                "2",
                "Wrong address listed",
                "",
                "At hub",
            ],
        ],
        [
            "20",
            [
                "20",
                "",
                "3595 Main St",
                "Salt Lake City",
                "UT",
                "84115",
                "10:30:00",
                "37",
                "Must be delivered with 13 & 15",
                "",
                "At hub",
            ],
        ],
        [
            "31",
            [
                "31",
                "",
                "3365 S 900 W",
                "Salt Lake City",
                "UT",
                "84119",
                "10:30:00",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
    ],
    [
        [
            "10",
            [
                "10",
                "",
                "600 E 900 South",
                "Salt Lake City",
                "UT",
                "84105",
                "EOD",
                "1",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "21",
            [
                "21",
                "",
                "3595 Main St",
                "Salt Lake City",
                "UT",
                "84115",
                "EOD",
                "3",
                "None",
                "",
                "At hub",
            ],
        ],
        [
            "32",
            [
                "32",
                "",
                "3365 S 900 W",
                "Salt Lake City",
                "UT",
                "84119",
                "EOD",
                "1",
                "Delayed on flight---will not arrive to depot until 9:05 am",
                "",
                "At hub",
            ],
        ],
    ],
]
