first_optimized_truck_index = [
    "0",
    "20",
    "21",
    "21",
    "21",
    "17",
    "2",
    "5",
    "18",
    "15",
    "6",
    "19",
    "12",
]

first_optimized_truck_list = [
    {
        "package_id": "14",
        "location_id": "20",
        "address": "4300 S 1300 E",
        "city": "Millcreek",
        "state": "UT",
        "zip": "84117",
        "deadline": "10:30:00",
        "weight": "88",
        "note": "Must be delivered with 15 & 19",
        "delivery_start": "8:00:00",
        "delivery_status": "8:06:00",
    },
    {
        "package_id": "15",
        "location_id": "21",
        "address": "4580 S 2300 E",
        "city": "Holladay",
        "state": "UT",
        "zip": "84117",
        "deadline": "9:00:00",
        "weight": "4",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "8:13:00",
    },
    {
        "package_id": "16",
        "location_id": "21",
        "address": "4580 S 2300 E",
        "city": "Holladay",
        "state": "UT",
        "zip": "84117",
        "deadline": "10:30:00",
        "weight": "88",
        "note": "Must be delivered with 13 & 19",
        "delivery_start": "8:00:00",
        "delivery_status": "8:13:00",
    },
    {
        "package_id": "34",
        "location_id": "21",
        "address": "4580 S 2300 E",
        "city": "Holladay",
        "state": "UT",
        "zip": "84117",
        "deadline": "10:30:00",
        "weight": "2",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "8:13:00",
    },
    {
        "package_id": "20",
        "location_id": "17",
        "address": "3595 Main St",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84115",
        "deadline": "10:30:00",
        "weight": "37",
        "note": "Must be delivered with 13 & 15",
        "delivery_start": "8:00:00",
        "delivery_status": "8:30:00",
    },
    {
        "package_id": "29",
        "location_id": "2",
        "address": "1330 2100 S",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84106",
        "deadline": "10:30:00",
        "weight": "2",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "8:44:00",
    },
    {
        "package_id": "1",
        "location_id": "5",
        "address": "195 W Oakland Ave",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84115",
        "deadline": "10:30:00",
        "weight": "21",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "8:53:00",
    },
    {
        "package_id": "40",
        "location_id": "18",
        "address": "380 W 2880 S",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84115",
        "deadline": "10:30:00",
        "weight": "45",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "8:57:00",
    },
    {
        "package_id": "31",
        "location_id": "15",
        "address": "3365 S 900 W",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84119",
        "deadline": "10:30:00",
        "weight": "1",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "9:03:00",
    },
    {
        "package_id": "13",
        "location_id": "6",
        "address": "2010 W 500 S",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84104",
        "deadline": "10:30:00",
        "weight": "2",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "9:22:00",
    },
    {
        "package_id": "37",
        "location_id": "19",
        "address": "410 S State St",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84111",
        "deadline": "10:30:00",
        "weight": "2",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "9:33:00",
    },
    {
        "package_id": "30",
        "location_id": "12",
        "address": "300 State St",
        "city": "Salt Lake City",
        "state": "UT",
        "zip": "84103",
        "deadline": "10:30:00",
        "weight": "1",
        "note": "None",
        "delivery_start": "8:00:00",
        "delivery_status": "9:36:00",
    },
]
